### ISSUE TITLE
1.7.10 mod list in ping not working with Thermos

### ISSUE THREAD

**Issue by kmecpp** [PaperMC/Travertine#96]
I have Travertine set up with a 1.7.10 Thermos server but for some reason the Travertine server ping shows a forge server with zero mods. It shows this whether or not the backend server is on or off and I have `ping_passthrough` enabled.

![image](https://user-images.githubusercontent.com/6520738/53189499-a5f34300-35d5-11e9-9268-39fb4c4be2ae.png)
![image](https://user-images.githubusercontent.com/6520738/53189529-b7d4e600-35d5-11e9-90f3-923601525172.png)

I believe the client sends their mod list first in the ping. Maybe it would be best if Travertine can always respond with an identical mod list?

Here is my Travertine config:

```
forge_support: true
connection_throttle_limit: 3
timeout: 30000
online_mode: true
log_commands: false
listeners:
- query_port: 25577
  motd: '&aOfficial Server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: true
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 100
  tab_size: 60
  force_default_server: false
  forced_hosts:
    pvp.md-5.net: pvp
connection_throttle: 4000
groups:
  kmecpp:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
network_compression_threshold: 256
inject_commands: false
disabled_commands:
- disabledcommandhere
stats: 52913098-d532-497b-850b-b5b958a19d0c
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
servers:
  lobby:
    motd: '&1Just another Travertine - Forced Host'
    address: localhost:25001
    restricted: false
player_limit: -1
```
